name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build Say Hello
        working-directory: ./packages/say-hello
        run: npm ci
      - name: Build Say Goodbye
        working-directory: ./packages/say-goodbye
        run: npm ci


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@fjordskii'
      - name: Publish Say Hello
        working-directory: ./packages/say-goodbye
        run: npm publish
      - name: Publish Say Goodbye
        working-directory: ./packages/say-goodbye
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}